language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm install gitbook-cli -g
env:
  global:
  - GH_REF: github.com/concretesolutions/cs-devops-training.git
  - secure: "C8WQD34+4JFSFntIF7HsVp/H0+sHSqEGZy78DOHysmVNw03bw7qoOPkDTglwYdgwc6gZYN4RY3xweCiksLzdVptOES4WcSXcHGLYrTOO4QaFfDvrVFDccyjBUvKbclWr8cSluMbJThez97TWIfBrKhKarmpmpT1Ut2GzKx/f3Zet20yTCnvi1ApVlfLxmS1przORD/AUW1GX/Xi8hkSZ99J8x+ycCsLAwcoJUgxC3kmZ7A2M5Kd7rxyTViO8ptKgr3vH8RYSjnNTUsFBxl48teH11WF1x7Pn4ns46/NobX+JOmkX/t+APcRoDXC5YlyiVLu+ASzmqZo6h8wX1sJdOt4wRA5pHCGVI1ILYw4i6kVHryRPQGoeBrF8GiYbdEEuGl1Z6jPd0U/MXGBXAE1gwRU6XmZnK7eOhEfNirIHWhhV5ThHYm16vjZfEwdQObu6nDm7lbkwE2/OztD08t/HwL4H0pymA3akH35GQGcAqtBAjpsBE6WGyZ845PkAdhRIsWjtEkAWpJ5/F7I8wtI8Eh9zBevOC8ALLOX2PIYS8fuTAABd5P8NYdmzSBf6SOnlLDp1NdY0o+7ial65jKTC8zsBTnTXvat4v+uujWXIAuCC6bLPjOIZC5QE2p6nmQSlZsYXUEX0iayrpGm/7bd+3wyPhrK4qoC3wWikS2sdfDY="
after_success:
  - bash deploy.sh
