language: node_js
node_js:
  - '0.11'
  - '0.10'
before_install:
  - npm install gitbook-cli -g
after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git add . 
  - git commit -am "Travis Update Doc." 
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
